### ISSUE TITLE
How to generate vector tiles from RAWR tiles ?

### ISSUE THREAD

**Issue by KAI10** [tilezen/raw_tiles#25]
I was able to generate RAWR tiles by running `rawr-process` in `tilequeue` repository. However, i am not sure how to use these RAWR tiles to generate vector tiles. Do i use code from this repository, or is there any example available showing how to do that?

**Comment by zerebubuth** [comment]
You can use the [`meta-tile` command](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/tilequeue/command.py#L2463-L2470) or the [`tile` command](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/tilequeue/command.py#L2423-L2429) from `tilequeue` to generate either a "meta tile" (package of several adjacent tiles) or a single tile, respectively. Your `config.yaml` needs to be set up to [use RAWR tiles](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/config.yaml.sample#L381-L382) by setting `use-rawr-tiles: true` and the [`rawr.source` section](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/config.yaml.sample#L326-L330) needs to point to where the RAWR tiles are stored. (See [the source code](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/tilequeue/query/__init__.py#L85-L91) for more info on how to configure the `rawr.source` section.)

Hope that helps!

**Comment by KAI10** [comment]
Thanks, I was able to generate vector tile using `tile` command. However, when i generate vector tile (in json format) from rawr tile, it takes about 36 seconds, where generation from postgresql database takes around 3 seconds. Coordinate of the tile was 10/768/442. Is this normal ?

**Comment by zerebubuth** [comment]
Yes, generating a single tile from a RAWR tile can be very slow, especially for RAWR tiles with lots of data in them. If you want to generate a small number of individual tiles, or generate tiles on-demand, then I'd recommend not using RAWR tiles and using the database directly.

The reason for this is that RAWR tiles were designed to be plain data and are not indexed by the `min_zoom` of the individual features. The idea was that it could change without needing to regenerate the RAWR tiles. When a RAWR tile is loaded, `tilequeue` calculates a `min_zoom` for every feature and spatially indexes it. This means that subsequent operations can be very fast, but there's an up-front cost to be paid. So the first tile might take 36 seconds, but the second should take much less - hopefully less than 3!

PostgreSQL has already paid this `min_zoom` calculation and indexing cost when we imported the data, so it is able to return results without delay.

Generally, when we use RAWR tiles it's for large-scale batch generation and we group jobs by the RAWR tile they're part of, so we can amortize the indexing cost over many tiles (85 per z10 RAWR tile in our current configuration). This means we can run all those jobs concurrently without overloading the (small cluster of) PostgreSQL databases.

**Comment by nvkelso** [comment]
Triaged some of this into the [wiki](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service), please followup with additional questions.

**Comment by KAI10** [comment]
Thanks for the detailed explanation. For the next step,  how do i run the process so that tiles that are part of a single rawr tile are generated together, sharing the indexing cost ? Here's what i tried:

I used the [enqueue-tiles-of-interest-pyramids](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/tilequeue/command.py#L2431) command to create a queue (of type file). The queue seemed to contain tile coordinates in a hierarchical manner (according to their zoom level). I copied one such group into a file [tile_queue_file_group.txt](https://github.com/tilezen/raw_tiles/files/2173504/tile_queue_file_group.txt) and used it as a queue. Then i ran the [process](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/tilequeue/command.py#L2332) command with [use-rawr-tiles](https://github.com/tilezen/tilequeue/blob/ab36dc4ff4dcb9f5fed11db826300de0200e4fc1/config.yaml.sample#L364) set to `true`.

However, it seems each tile is taking large amount of time to be generated where i was expecting, starting from the second tile, generation time would be low.

**Comment by zerebubuth** [comment]
That sounds like it should work, but there's a couple of things which might be complicating the process.

1. To keep tiles together with other tiles generated from the same RAWR tile, the code enqueues groups of tile coordinates in the same message payload. For the `file` type of queue, each payload is a separate line and this means that the file should have multiple coordinates (written `z/x/y`) per line, separated by commas. If you only see one coordinate per line, then you might need to switch to the `multiple` message marshaller in the [`message-marshall` section of the config](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/config.yaml.sample#L25-L28).
2. Lower zoom tiles generally take longer to process than higher zoom ones because there's more data in them, and there's much more processing done on that data. To test this, you could try deleting the lower zoom tile coordinates in the `tile_queue_file_group.txt` and seeing if the higher ones are generated as fast as you think they should be.

The queueing system in `tilequeue` is what we used to use, but we've since switched to AWS Batch, which doesn't use the same system. Instead of grouping messages in queues, we group whole tile pyramids of tiles together in a "job". We generally group at z7 and the job is run using the [`tilequeue meta-tile`](https://github.com/tilezen/tileops/blob/master/docker/meta-batch/Dockerfile#L24) command. To use this to generate all the tiles from a z10 RAWR tile, I would set the `batch.queue-zoom` config setting to `10`, and run `tilequeue meta-tile --config config.yaml --tile z/x/y` with the `z/x/y` of the RAWR tile. That should ensure that the RAWR tile is indexed only once.

If it's still slow, you could try putting a breakpoint or print statement on [the RAWR tile index generating code](https://github.com/tilezen/tilequeue/blob/4062c1a579bdf965a4ebc711f238d8b37de8b926/tilequeue/query/rawr.py#L580) to check if it's being called multiple times.

Hope that helps!

**Comment by KAI10** [comment]
Successfully batch generated vector tiles from rawr tiles with reasonable run time. I had the issue you mentioned in 1.
